2021-08-11 15:19:14,207 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:19:18,765 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:20:29,147 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:20:32,868 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:21:20,368 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:21,806 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:22,281 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:22,554 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:22,846 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:23,054 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:23,386 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:23,656 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:23,896 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:25,519 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:21:25,544 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:25,737 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:25,893 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:25,967 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:26,095 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:26,240 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:26,384 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:26,475 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:26,616 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:26,758 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:26,899 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:26,996 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:27,140 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:21:51,742 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:23:00,390 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:23:35,184 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:25:12,435 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:25:12,596 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:25:12,660 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:25:12,771 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:25:12,836 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:25:12,842 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:25:12,849 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:25:12,979 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:26:13,774 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:26:13,934 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:26:14,030 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:26:14,040 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:26:14,049 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:26:14,204 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:26:14,295 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:26:50,312 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:26:55,259 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:27:12,809 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:12,965 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,058 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,306 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,352 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,362 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,416 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,425 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,444 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,454 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,463 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,476 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,486 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,494 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,502 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,509 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,622 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,793 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,900 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,906 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,912 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,918 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,924 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:13,939 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:31,190 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:31,219 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:31,346 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:31,425 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:31,569 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:31,649 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:31,851 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:31,992 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,002 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,010 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,019 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,025 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,031 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,038 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,044 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,050 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,056 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,064 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,070 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,077 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,084 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,091 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,097 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:32,104 - [ERROR] - File "cathaypacificcargo\awb_detial_query.py", line 110, in queryTask: [AttributeError] 'NoneType' object has no attribute 'text'
2021-08-11 15:27:58,321 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:28:00,783 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:28:25,991 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:29:04,895 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:30:07,635 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:30:10,434 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:30:41,321 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:31:15,300 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:31:19,418 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:31:22,931 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:31:30,172 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:31:32,268 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:31:34,733 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:31:44,683 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:31:49,302 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:31:51,618 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:31:53,856 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:32:22,063 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:32:25,605 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:32:31,047 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:32:45,383 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:32:50,326 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:33:12,456 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:33:49,994 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:33:57,123 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:34:06,957 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:34:12,491 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:34:17,068 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:34:19,320 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:34:27,331 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:34:30,809 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:34:35,015 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:34:39,063 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
2021-08-11 15:35:34,117 - [ERROR] - File "C:\Python36\lib\site-packages\pyppeteer\launcher.py", line 133, in _cleanup_tmp_user_data_dir: [OSError] Unable to remove Temporary User Data
